name: "Deprecated API Scan"
description: "Scan for deprecated API calls"
inputs:
  python-version: # version of Python to run
    description: "Python version, in the format MAJOR.MINOR"
    required: true
    default: "3.7"
  pylint-version: # version of Python to run
    description: "Python version, in the format MAJOR.MINOR"
    required: true
    default: "2.9.4"
#outputs:
#  results-file: # id of output
#  description: "Path to results file"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        lfs: true
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ inputs.python-version }}
    - run: |
        pip install --upgrade pip setuptools wheel
        pip install pylint==${{ github.pylint-version }}
      shell: bash
    - run: |
        echo 'ls -la'
        ls -la
        echo "PWD: ${PWD}"
        echo "GITHUB_WORKSPACE: ${{ github.workspace }}"
      shell: bash
