name: Publish Github Pages

on:
  workflow_call:
    inputs:
      python-version:
        #python version is required in order to make sure that the package can be built
        required: true
        type: string

jobs:
  publish-docs:
    name: "Publish Github Pages"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      # Checkout the code
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          # require all of history to see all tagged versions' docs
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install Dependencies
        run: |
          python3 -m pip install poetry
          poetry install

      - name: Checkout gh-pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: docs/_build

      - name: Build Docs
        run: |
          poetry run sphinx-mutliversion docs/sources html
          touch docs/_build/.nojekyll
          ls -l
          ls -l docs
          ls -l docs/_build

      - name: Publish Docs to gh-pages
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build
          keep_files: true