name: Publish Github Pages

on:
  workflow_call:
    inputs:
      python-version:
        #python version is required in order to make sure that the package can be built
        required: true
        type: string

jobs:
  publish-gh-pages:
    name: Publish Github Pages
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install Dependencies
        run: |
          python3 -m pip install poetry
          poetry install

      - name: Checkout gh-pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: docs/_build

       - name: Build Docs
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/development' || startsWith(github.ref, 'refs/tags')
        run: |
          poetry run sphinx-mutliversion docs/sources html
          touch docs/_build/.nojekyll
          ls -l
          ls -l docs
          ls -l docs/_build

      - name: Publish Docs to gh-pages
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/development' || startsWith(github.ref, 'refs/tags')
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build
          keep_files: true