# This workflow will add 2 jobs:
# - check-format: checks whether any files would be reformatted by `black`
# - test: runs `pytest`.  Uses `pipenv`, `poetry`, or `pip` depending on the files present

name: PyPI Publisher

on:
  workflow_call:
    inputs:
      # Python version is required in order to make sure that pytest and black can be run correctly
      python-version:
        required: true
        type: string
    secrets:
      PYPI_TEST_TOKEN:
        required: false
      PYPI_PROD_TOKEN:
        required: false
      ARTIFACTORY_USER:
        required: false
      ARTIFACTORY_PASSWORD:
        required: false
      ARTIFACTORY_URL:
        required: false

jobs:
  pypi-publish:
    name: PyPI Publish
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python-version }}
      - name: Validate Package Manger
        # Stop GA if both setup.py and poetry.lock are present
        # We dont know which one to use
        run: |
          if [[ -f setup.py && -f poetry.lock ]]; then
            echo "Both setup.py and poetry.lock exists. Only one of them must be present."
            exit 1
          fi

      - name: Build Package using Poetry
        if: hashFiles('poetry.lock') != ''
        run: |
          echo "Building Package"
          python3 -m pip install --upgrade pip setuptools wheel
          python3 -m pip install poetry
          python3 -m poetry build

          echo "\nValidating Build Version"
          build_version=$(ls dist/*tar.gz | awk -F"-" '{ print $2 }' | awk -F".tar" '{ print $1 }')
          github_release_version=$(echo $GITHUB_REF_NAME | tr -d 'v')
          echo "Build Version: ${build_version}"
          echo "Github Release version: ${github_release_version}"
          if [[ "$build_version" != "$github_release_version" ]]; then
            echo "Release Version mismatch. Stopping..."
            exit 1
          fi

      - name: Build Package using setup.py
        if: hashFiles('setup.py') != ''
        run: |
          echo "$PWD"
          ls -l $PWD
          echo "\nBuilding Package"
          python3 -m pip install --upgrade pip setuptools wheel build
          python3 -m build


          echo "\nValidating Build Version"
          build_version=$(ls dist/*tar.gz | awk -F "-" '{ print $2 }' | awk -F ".tar" '{ print $1 }')
          github_release_version=$(echo $GITHUB_REF_NAME | tr -d 'v')
          echo "Build Version: ${build_version}"
          echo "Github Release version: ${github_release_version}"
          if [[ "$build_version" != "$github_release_version" ]]; then
            echo "Release Version mismatch. Stopping..."
            exit 1
          fi

      - name: Publish package to test pypi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TEST_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
